### ISSUE TITLE
Empathy broken in Null & Light Pink

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#1015]
kakashi's null 5 is negative 1, 2, 3, 4, 5
known to be a null card now
![e](https://user-images.githubusercontent.com/50160641/81281949-1bd5b400-908d-11ea-9e05-6a29d7386131.png)

**Comment by padiwik** [comment]
Non-null suits are now crossed out when the card receives negative rank for every rank like here. But this only happens when `possibilitiesCheck()` is run, i.e. not in speedruns. I'm not sure if we want the suit pip to be actually removed, which seems like the choice more consistent with the rest of empathy.

**Comment by Zamiell** [comment]
yes, that sounds like a bug, it should be consistent with the rest of empathy

**Comment by Zamiell** [comment]
padi says this is fixed
