### ISSUE TITLE
better keyboard shortcuts

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#125]
It would be nice if you can perform any action with 2-3 keyboard shortcuts. 
For example (I don't know whether these keys are the best):
12345 is play slot 1-5
qwert is discard slot 1-5
asdfg is select number clue 1-5
zxcvbn is select color clue blue, green, yellow, red, purple, orange (the possible color clues from left to right)
hjkl to select player to clue
enter/return to confirm action.

Examples: 
* 1-enter to play slot 1
* r-enter to discard slot 4
* z-h-enter to clue blue to the player to your left
* l-c-enter to clue yellow to the player to your right (in a 5-player game)

**Comment by rogers-j** [comment]
Rank clues are bound to 1-5
Color clues are bound up to QWERTY

There is a separate issue to make ctrl-enter confirm a clue because Zamiel thought just Enter was too easy to hit by accident. (This was not a problem until the client remembered the previous clue.)

Plays and discards use a prompting system, but that's just an extra key to start the sequence. Then it uses slot numbers. The enter key does confirm that prompt.

Currently the clue target cycles with tab. In a 3 player game that's 0-1 key, up to 0-3 in a 5 player game. We could bind it to ASDF as well.

For pure speed of play, pre-play is still my suggestion.

The current hotkey system works with the existing UI, rather than add new complexity or ignore it entirely. We should not be looking to save time at the expense of user responsiveness.

**Comment by fpvandoorn** [comment]
I just tested the keyboard shortcuts a bit. The current ones are probably fine. However, I noticed two issues:

* I was not able to confirm giving a clue, enter, ctrl+enter or anything else I tried didn't work
* The "a" and "d" keys often didn't work. If I alt-tabbed into a window, and then pressed either of those keys, they didn't trigger (pressing "+" or "-", or for some reason CAPS LOCK + "a" or CAPS LOCK + "d" worked consistenly, I think)

**Comment by Zamiell** [comment]
12345 is play slot 1-5
qwert is discard slot 1-5
!@#$% is clue number 1-5
QWERTY is clue color 1-6

**Comment by Zamiell** [comment]
and you must check the new checkbox in the lobby settings

**Comment by Zamiell** [comment]
also, pressing a keyboard shortcut will queue the action if it is not your turn
