### ISSUE TITLE
/setleader becomes accessible to a non-leader when he is away

### ISSUE THREAD

**Issue by feydriva** [Zamiell/hanabi-live#1613]
Hi, is it possible that this command: /setleader becomes accessible to a non-leader when the leader is away?
https://github.com/Zamiell/hanabi-live/blob/master/docs/CHAT_COMMANDS.md#pre-game-game-and-replay-commands-table-owner-only
When the leader has a disconnection or has left it will be fine.
Thanks

**Comment by Zamiell** [comment]
if leader disconnects, they will automatically leave the table, which will automatically pass the leader to someone else

if the leader is away, that means they explicitly want to leave the table temporarily without leaving it permanently, which presumes that they would not want someone else to steal the leader role away from them

**Comment by marcmagus** [comment]
This presumes that all leaders are equally conversant with the software, which means of leaving the table will pass leadership, and never, say, has to take a phone call and makes a mistake.

Is the cost of risking that sometimes leadership will be stolen in a cooperative recap and the group can't resolve that social situation higher than risking that sometimes the rest of a group will be stuck unable to complete a recap because something happened with the leader?

**Comment by Zamiell** [comment]
are you referring to a pregame or a shared replay?

**Comment by Zamiell** [comment]
anyways, i've now enabled setting the leader by anyone, although it might get reverted in the future if it is abused

**Comment by feydriva** [comment]
Cool, thanks!
