### ISSUE TITLE
future efficiency is bugged

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1833]
#340413
turn 18

**Comment by timotree3** [comment]
How so? Looks normal to me.

**Comment by Zamiell** [comment]
sorry its turn 50
when kakashi blind plays y1, the eff goes up.
why would blind playing a card make the future eff go up

**Comment by timotree3** [comment]
that's intended. if y1 is played in the final round then it is possible to play five 5's before the final round, thus gaining 5 clues from 5s. if y1 is played now then it is only possible to play four 5's before the final round. thus gaining 4 clues from fives. although "Cards gotten" increases, so does "Clues still usable" decrease. 9/6 < 8/5

**Comment by Zamiell** [comment]
> if y1 is played in the final round then it is possible to play five 5's before the final round

what

**Comment by Zamiell** [comment]
if kim waited until the very last round of the game until she played the y1, how would that allow the team to play an extra 5 on the stacks?

**Comment by timotree3** [comment]
the algorithm envisions a final round of y1-y2-y3-y4-y5 in which only one clue is wasted from playing a 5 in the final round. if such a final round where possible, then every 5 besides yellow could be played beforehand, thus gaining more usable clues than otherwise.

after y1 is played, now the best imaginable final round is x5-y2-y3-y4-y5 in which two 5's are played, thus wasting 2 clues

**Comment by Zamiell** [comment]
wild

**Comment by timotree3** [comment]
I even wrote a test for this exact behavior. 

https://github.com/Zamiell/hanabi-live/blob/45c4069b4eaf6eb68db3e778a5c366ead3f86a1d/client/src/game/rules/stats.test.ts#L173-L180
