### ISSUE TITLE
in-game hypo

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1882]
1. Enter any currently running game
2. Open hypo
3. Drag cards until you get this state:
![image](https://user-images.githubusercontent.com/46625461/99918066-7aab0400-2d25-11eb-807c-fe61c8e88f6d.png)
4. Play/discard
5. Enjoy
![image](https://user-images.githubusercontent.com/46625461/99918054-67983400-2d25-11eb-802d-7dd8c85285a9.png)

**Comment by timotree3** [comment]
you have to morph the card before you try to play it. If the game doesn't know what card you have then how can it show a hypothetical gamestate after it is played?

It is planned to prompt the user for the identity of the card they are trying to play. 

Progress related to this issue is already tracked in the first bullet point of #1876

**Comment by Zamiell** [comment]
tim should i close this now?

**Comment by timotree3** [comment]
Yeah

**Comment by Zamiell** [comment]
hokay
