### ISSUE TITLE
Safari and ios doesn't work anymore

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1931]

**Comment by padiwik** [comment]
be specific... the lobby doesn't load?

**Comment by Aigul9** [comment]
yes

**Comment by jack67889** [comment]
iOS? Because ‘Chrome’ on iOS is basically still Safari. But since the day before yesterday the site stopped working on Safari (at least iOS and macOS).

After entering your credentials you get the internet hiccup/server restart error. Console error attached if it helps.  

<img width="1920" alt="4421E37D-6FAA-43DA-9643-09CE9B76ED7B" src="https://user-images.githubusercontent.com/74204920/100976363-b02ec900-353f-11eb-9b0d-8cb8b4ce3a75.png">

**Comment by Aigul9** [comment]
@jack67889 and other browsers too?

**Comment by jack67889** [comment]
Yeah, it’s basically all Safari on iOS.

**Comment by padiwik** [comment]
https://stackoverflow.com/a/36097177

**Comment by jarhill0** [comment]
Specifically in this case it seems to be the `X-Rate-Limit-Request-Forwarded-For:` header that's empty, and I believe that header is coming from [tollbooth](https://github.com/didip/tollbooth).

**Comment by Zamiell** [comment]
oh thats interesting

**Comment by Zamiell** [comment]
i'll just disable tollbooth for now

**Comment by Zamiell** [comment]
can you describe how you found this

**Comment by Zamiell** [comment]
fixed for now
