### ISSUE TITLE
passworded game allows unauthenticated watchers

### ISSUE THREAD

**Issue by patricksheehan** [Zamiell/hanabi-live#2058]
I started a game then shared a turn link (e.g. https://hanab.live/game/338#21) to a friend who wanted to spectate, and then we noticed another person joined to watch our game and neither needed to enter the game password. Is this behavior expected?

**Comment by Zamiell** [comment]
yup, it is expected.
the password protection thing is just so that you don't have strangers joining your games.
but having strangers watch is pretty harmless.
i think if a spectator joins your game and starts talking shit or something in the chat, then you can boot them by typing `/kick alice`
and feel free to report them to me and ill ban them
