### ISSUE TITLE
UDD which of the two do you think is a cm ?

### ISSUE THREAD

**Issue by mmelwen** [Zamiell/hanabi-live#2175]
![image](https://user-images.githubusercontent.com/66402571/115789779-58014200-a3ce-11eb-988e-9da685803636.png)

https://hanab.live/replay/509002#1

First turn of the game I give yellow to Lel and so now he knows that are both the same card. Which card should Lel discard?
There are two contradicting thoughts,

1) should discard the focus of the clue, like UTD
2) should discard the left because is how we discard trash

I believe that this should be defined and the other one should be a cm.

**Comment by Lel0uch-H** [comment]
In addition to this, if the focus of a UDD is on chop, touches exactly 2 cards and they are both known to be dupes to the clue receiver but not globally, the problem becomes even more complex.

Looking for more opinions on choosing how to define the discard order in such cases.

**Comment by timotree3** [comment]
Obviously the expected discard order should be discarding the card that is guaranteed trash by a blind play (the focus of the clue) before any other cards. This also applies to trash bluffs, and is [included in the doc](https://hanabi.github.io/docs/level-13/#the-trash-bluff):

> In the case where multiple cards are clued as part of a Trash Bluff, all of the touched cards are considered to be trash. However, the focus of the clue should be the first thing discarded, which allows for the possibility of your teammates to give a follow-up Fix Clue.

If the card besides the focus of the clue is discarded, then that should be a trash order chop move, because just communicating that the clue receiver know it's not a UTD because they see all the copies of those cards is not valuable.

Here are two in-game examples where blindly obeying left to right discard order leads to confusion/missed opportunities with chop moves:

1. https://github.com/hanabi/hanabi.github.io/issues/419#issuecomment-823348262
2. https://hanab.live/replay/482822#11
   timotree has two clued 1's that were clued as a trash chop move. They are known trash because kinkajusrevenge has a copy of m1 clued. If the focus of the clue is rainbow 1, then kinkaju thinks it's a play clue, not a trash order chop move, therefore it's important to discard the focus of the clue (slot 3) first to keep kinkaju in sync. timo discards slot 3, and half of the players write [cm] on orucsoraihc's chop, believing that timo was expected to discard slot 2.

**Comment by timotree3** [comment]
Also, this belongs on the conventions repository, github.com/hanabi/hanabi.github.io not the website repository github.com/Zamiell/hanabi-live
