### ISSUE TITLE
DDA detection still plays the double-discard sound even when it shouldn't

### ISSUE THREAD

**Issue by mdavidson29** [Zamiell/hanabi-live#2222]
The new code that shows question marks when cards are at risk of double-discards isn't properly integrated with the double-discard sound.  

As an example, the 4-tone double-discard sound was played even when g4 was discarded immediately after r4, despite having negative-red information on this card.  
![2](https://user-images.githubusercontent.com/30240608/125898809-505f1615-212d-4a21-b813-3bb9cbea7f0f.jpg)
![1](https://user-images.githubusercontent.com/30240608/125898812-06cb5c76-1d6a-468e-9a2b-349d9e40f512.jpg)

**Comment by vEnhance** [comment]
I think there's a question of when exactly we want the sound to play, because the question marks depend on asymmetric information.

For example: Alice discards g4. Bob sees the other g4 in Cathy's hand, so Bob discards anyways, and Cathy marks her hand for g4 elimination notes.

The four-tone sound certainly plays for Cathy. The question is whether it should also play for Alice and Bob, to remind the team that elimination notes should be written.

**Comment by mdavidson29** [comment]
That's a really good question!  I think it makes sense for it to play for Alice and Bob as well, because that discard meant something extra.  

So I think here are the cases:
- If it's universally known to be a safe discard (e.g. the game I showed above), then the tone should not play
- If it's not universally known to be a safe discard (e.g. the situation you just described), the tone should play for everyone

Does that make sense?

**Comment by Zamiell** [comment]
both the sounds and the question mark icons are intended to be based on globally known information only

**Comment by vEnhance** [comment]
Man, my memory is real awful, but I finally remembered the reason why I kept the status quo for sounds. The answer is: **chop moves**.

In the screenshot you showed, the client doesn't know if the green card was chop moved or not, which would affect DDA determination. So, that's why when I designed the question marks, I decided explicitly to leave the sound alone. The plan was the game would play a sound *if* the discarded card *could* be in Bob's hand, and then all players have to check for themselves whether the card is actually on chop or not.

There is one way we could still make this feature request work. As of #1919 (also from yours truly), the game state *does* keep track of some minimal basic information about the player notes --- we needed this because we wanted our future efficiency calculation to include cards that were noted as gotten. It looks like I had the good foresight to include the "chop move" among that information, so we could make it work.

But with that said, I am not sure I would *want* to implement this, for the following reasons:

1. I am nervous about the resulting asymmetry; if Carol thinks Bob is chop moved and Donald doesn't, then the sound might play for one of Carol/Donald but not the other. (This is true for the required efficiency counter too, but I think that's less of a big deal since that number is for private advisory purposes, whereas DDA changes clue interpretations.)
2. To do this correctly with globally know information, one might need sudoku inference: maybe g4 got discarded and Bob has g34. But Carol has g3 and Donald has g3. Then Alice knows Emily knows Bob knows Bob is not in DDA and that Carol and Donald don't know ... kind of thing. I guess maybe we could just use pure negative information instead and have it be right in 99% of cases lol.

Nonetheless, my inclination is that KISS might be better here. In the status quo, people hear an extra sound and see the question marks, and just go "haha website bug" and that's all. The alternative seems like a bit of extra code complexity and some tiny chance of confusion. Neither of the pros nor cons is a big deal imo but the pro seems so tiny I am having trouble justifying it.

I'm open to having my mind changed about this since #1919 makes this possible to implement. But I'd want to first have an agreement on whether it's worth it, and if so, a specification of how we want to do it.

**Comment by Zamiell** [comment]
evan we discussed this already and we decided that
1) we don't want the client to derive where your chop is from notes, because it could be inaccurate
2) we want all of the sounds to be globally synchronous

if the question marks are showing something different than the sounds, then that's a bug, and the question marks need to be adjusted

**Comment by vEnhance** [comment]
> if the question marks are showing something different than the sounds

I'm not sure what you mean for the question marks to be *different* than the sounds because the question marks are on a per-card basis, the sound are not.

Specifically, algorithm right now is:

* if the penultimate copy of a non-trash card is discarded and the other copy isn't filled in somewhere else, then play DDA sound.
* if DDA sound plays, then mark all cards in Bob's hand with a question mark if they could be the discarded card, based on `cardRules.canPossiblyBe` (i.e. globally known info).

My understanding is that's what you (Zam) want.

Whereas here mdavidson seems to be commenting that if the chop card has no question mark, the sound shouldn't play. My response was that we can't do this cleanly without deriving chop moves from clues.

Well, there might be cases where _none_ of Bob's cards have question marks, so there should be no sound no matter what. I'm rereading the `statRules` (not by me) and I _think_ this check was never implemented for the sound. I can do this, but I think that's a different (but related) issue; I also am not convinced this case occurs frequently enough to be worth the extra code complexity either.

**Comment by Zamiell** [comment]
there are two different sounds:

1) the "discarded to initiate a double-discard situation" sound
2) the "discarded IN a double-discard situation" sound

mdavidson is commenting about #2, not #1.
#2 should never trigger if a non-question-mark-card is discarded, right?

**Comment by vEnhance** [comment]
Oh.

You are exactly right. I misunderstood the issue.

I agree that's a bug. Will look at.

**Comment by Zamiell** [comment]
thank you for looking into it!

**Comment by vEnhance** [comment]
The bug comes from the definition of `{ lastAction } = ...` in `getSoundType`. The previous code tried to check `lastAction.type === "discard"` but in fact `lastAction.type` seems to always equal `"turn"`.

In just a moment I'll push a PR that uses `cardRules.canPossiblyBe` on `originalState.deck[originalState.stats.doubleDiscard]` now that we have this new variable from the question mark code.
