### ISSUE TITLE
Matching variant should be displayed first

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2280]
![2021-11-03_23-33-25](https://user-images.githubusercontent.com/46625461/140189509-da32ee0d-772c-4a03-81fc-117b7c384405.png)

**Comment by Zamiell** [comment]
define matching

**Comment by Aigul9** [comment]
look at the screenshot

**Comment by Zamiell** [comment]
i see the screenshot, which doesn't explain, which is why i asked the question

**Comment by Aigul9** [comment]
i want to see variant which starts with the same characters as my input in the first row

**Comment by Zamiell** [comment]
the first row is "test game", so i dont understand

**Comment by Aigul9** [comment]
first row in the list

**Comment by Zamiell** [comment]
the first row in the list of the found variants in the screenshot is "Omni & Dark Prism (5 Suits)", which is exactly what is already displayed, so i dont understand what you mean

**Comment by Aigul9** [comment]
and i am searching for dark prism and omni

**Comment by Aigul9** [comment]
it’s a bad ux when i have to look through the entire list to find it

**Comment by DrAnax** [comment]
This is the default behavior of browsers regarding datalist search. Contrary to what one might expect, showing elements starting with the given text was considered a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=153991) which was fixed.

Alternatively I tried to create an initial array of all variant values and filter them by using the user's input, as described [here](https://stackoverflow.com/questions/40456970/html-datalist-is-there-a-way-to-autocomplete-based-character-order) but, due to the size of the original list, the end result was extremely slow to be useful.

Can't fix.
