### ISSUE TITLE
Let's set the settings

### ISSUE THREAD

**Issue by DrAnax** [Zamiell/hanabi-live#2292]
In all proposals items are stacked on a single column on narrow screens

**Proposal 1:**
- each line is a different item
- items flow top to bottom
- constrain height to force wrap on next column

![image](https://user-images.githubusercontent.com/2622043/144020418-cf6fdf2a-1d86-4fc6-bd29-973817de8de1.png)

**Proposal 2:**
- settings are groupped
- items flow top to bottom
- constrain height to force wrap on next column

![image](https://user-images.githubusercontent.com/2622043/144020606-c0d3a359-79dc-4d08-83f3-3c9a36f1d351.png)

**Proposal 3:**
- settings are groupped and reordered via css to save space
- items flow top to bottom
- constrain height to force wrap on next column

![image](https://user-images.githubusercontent.com/2622043/144020946-4b758097-3ffc-4d0c-821a-1ab78d607e05.png)

**Proposal 4:**
- settings are groupped
- items flow left to right
- constrain width to force wrap on next row

![image](https://user-images.githubusercontent.com/2622043/144021279-82598fda-fefe-4e69-a357-3431543307b3.png)

**Proposal 5:**
(and now for something completely different™)
- settings are groupped and hidden
- user can open / close by clicking the title
- possible to close other items onopen via js (needs testing)

Edit: it can be done: https://codepen.io/DrAnax/pen/oNGNyMb

![image](https://user-images.githubusercontent.com/2622043/144021909-251d8917-c973-4bbf-903e-142eeef6a1e8.png)

**Comment by DrAnax** [comment]
I used too as well (actually, nr 3 which makes the settings modal more square-ish), but I feel that nr 5 is best. It takes the least screen space and it's very good for expansion.

**Comment by Zamiell** [comment]
5 seems like the worst option, because you force the user click up to an extra N times in order to explore and see what all the options are.
seems like bad UX

**Comment by DrAnax** [comment]
5 works like tabs and context menus, which are successful ux paradigms. It's the same principle: organise more information in less space.

Imagine having, say, 100 difference settings. Presenting all those to a new user in a single screen would alienate him, whereas organise them in logical groups would probably entice him to explore without overhelming him.

**Comment by Zamiell** [comment]
i agree that presenting 100 different options to a user would be overwhelming.
an excellent strategy to mitigate that feeling of being overwhelmed would be to collapse them into logical groups, like you say.
however, that is treating the *symptom* of the problem rather than treating the *cause* of the problem.
if there are 100 different options, the *cause* of the problem is that the website is bloated and has too many options.
my design philosphy is that i hate settings.
hanabi-live will never have 100 different settings.
as for what we currently have, if we currently need to employ any strategies to avoid overwhelming the user, then you need to tell me that so that i can delete some options
