### ISSUE TITLE
Detrimental Character games affect statistics

### ISSUE THREAD

**Issue by ConnorCMcD** [Zamiell/hanabi-live#2300]
Played some No Variant detrimental character games for the first time today and noticed afterwards that my strikeout rate was no longer 0%.  It's not a huge deal, but I would've assumed it wouldn't have been affected since speedrun games (which you also strikeout more often in due to trying to go fast) don't affect stats.

Ideally, I think it would be cool if stuff like speedruns and detrimental character games could have their own statistics.

**Comment by Zamiell** [comment]
> I think it would be cool if stuff like speedruns and detrimental character games could have their own statistics.

there are N variants and M game modification settings, and we don't want to keep track of statistics for N*M combinations.

> speedrun games (which you also strikeout more often in due to trying to go fast) don't affect stats.

this is by design because it is kind of pointless to keep stats for speedrunning since 99.9% games will result in a termination (assuming WR attempts, which is the default assumption).
