### ISSUE TITLE
when making a note, backspace works incorrectly

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#2344]
step 1 - make the following note on a card:
[y2] p

step 2 - right click the card again to bring up the note box

step 3 - press backspace

expected: only the pipe and space will be deleted
observed: the "p" character is deleted

**Comment by timotree3** [comment]
Backspace and left arrow both seem like they should have the same result: delete the pipe and leave the cursor at the end of the text.

**Comment by Zamiell** [comment]
yep

**Comment by DrAnax** [comment]
The idea is that special keys continue to function **and** remove the pipe; otherwise, if a player wants to delete the last letter of his note, you would have to press backspace twice, which is not what he expects to happen normally.

Those who wish to remove the pipe and continue typing they just have to press the right arrow or the del key.

By the way, I think it is better if we add the appearance of the pipe as an option in the player's settings.

Finally the prototype in Codepen was created as a test playground for the prototype. Better to finalize the product before going live, right?

**Comment by Zamiell** [comment]
> The idea is that special keys continue to function and remove the pipe; otherwise, if a player wants to delete the last letter of his note, you would have to press backspace twice, which is not what he expects to happen normally.

i disagree.
for example, if a player sees the following text:
```
a -
```
if the cursor is on the rightmost side of this text, then just by looking at it, the end-user will expect that **pressing backspaces will delete the hyphen**.

this is different from the case of pressing home.
in the case of pressing home, the end-user will expect that the cursor will go home.

**Comment by Zamiell** [comment]
> The idea is that special keys continue to function and remove the pipe

thus, currently, the code treats all special keys as equal, but it should not do this, because the correct behavior depends on what kind of special key is being pressed
