### ISSUE TITLE
Add a column "Turn count" on https://hanab.live/scores

### ISSUE THREAD

**Issue by mmelwen** [Zamiell/hanabi-live#2415]
Now with the weekly tournament 1 seed, which actually is very nice, (thank you Libster) we are training for 6-7 seeds, before we do the comp but in order to be able to see if would have get a good result we need to open 1 by 1 all the replays to see the turn count.

Isn't silly to do all this for every practice game, when the actual information is already stored in the DB??

Feels like some kind of compulsive punishment

**Comment by Zamiell** [comment]
we already decided against this because it implies normative value on turn count

**Comment by HelanaAsh** [comment]
I like this idea evry much for similar reasons. Zamiel have you tried opening tables manually and check turn counts for each? If there is no value for turn counts, why is such a critical factor at competitions?

**Comment by Zamiell** [comment]
see the other thread that discusses this

**Comment by padiwik** [comment]
The thread being referenced is in #hc-general starting here https://discord.com/channels/140016142600241152/712422871044980848/803494285508870165, where multiple members of the community argued for adding turn counts due to various reasons, in spite of how it might imply that turn count has a "normative value".
