### ISSUE TITLE
make function to prune users older than 6 months with no games played

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#247]

**Comment by RaKXeR** [comment]
this doesn't sound like a good idea, the best example would be losing the statistics of the retired players. There's not even a way to email people telling them their account is gonna be deleted since there's no email confirmation... I guess you could ping them a week before on discord if they have an associated discord account?

If you're dead set on implementing this, then it's best not to delete the accounts of anyone that has been assigned a role on our discord, that probably fixes most of the issues.

**Comment by Zamiell** [comment]
did you notice the last 4 words in the title of this issue?

**Comment by RaKXeR** [comment]
oh I thought you meant "no games played in the last 6 months", my bad.

**Comment by Zamiell** [comment]
done
