### ISSUE TITLE
Adding in Global Statistics

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#441]
I see how you can access your own or other player's statistics by clicking their username. 

Would it be possible to have a tab on the home page for global statistics where it's a compilation of everyone's statistics together?  Would be neat to see how many total games have been played in each variant.  

Would it also be possible to set it up so you can click the individual variants to display a completion history that you can organize by date, time, etc.?

**Comment by Zamiell** [comment]
are you a programmer?

**Comment by Dr-Kakashi** [comment]
Unfortunately, I'm not.  I've taken an intro course to C++ a while back, so I'm not really well versed atm.  Why are you asking?  What programming language does hanabi.live uses?

**Comment by zsole2** [comment]
I fully support the second idea, that is to be able to click on the ID/name of the variant in the player's statistics and show more details on the games played with this variant. 
I am not a programmer, either, but looking around in the code of the project it seems that this would be way more complicated than the solution you applied to the Full Game History tab. 
On the other hand, the Show History button in the Lobby already accomplishes this, for all the games of the player, therefore it just needs to be filtered by the variants. Then if you could show the filtered list of games in a similar way as in the History table, it would be halfway completing the new feature (of course, there would be no sorting available). 
Or could it be started from the History page, rather than from the statistics?
In any case, this would be immensely helpful for newbies, especially by allowing studying what expert players did in the same game (through Other Scores).

**Comment by Zamiell** [comment]
maybe i am misunderstanding your comment, but you can already find expert games of an arbitrary variant by going to someone's profile, clicking "Full Game History", and then doing ctrl+f for the variant you want

**Comment by zsole2** [comment]
Agree, your suggestion is perfectly workable. 
My process would be that if I played a variant several times, I list them all, and then would be able to check out how any specific game was played by others and look for possible improvements based on their play. The Show History list (and thus the listing of Other Scores of the same game) is only available right now by chunks of 10, rather than by the variant.

**Comment by Zamiell** [comment]
i added some global stats. open a new issue if there is a global stat missing that you want
