### ISSUE TITLE
"Back" button in replay

### ISSUE THREAD

**Issue by Asddsa76** [Zamiell/hanabi-live#495]
During shared replay, when you have to go back to a turn for various reasons (someone asks, look at boardstate when a clue was given, point out a past event, etc), and want to go back to the main timeline, we now have to search for the correct turn number, since the "Back" button was removed.

**Comment by Zamiell** [comment]
the old implementation was not useful. it sounds like you want the ability to mark a turn and then go back later?

**Comment by Asddsa76** [comment]
I believe it was useful. And the suggested marking doesn't work for: 

Shared replay is on turn 30. 
Bob: Hey, what about the clue on turn 15?
Goes to turn 15. Discusses. 
Alice: what turn were we on before this?

Unless you mark the turn before jumping back in time. But that seems backwards.

**Comment by Zamiell** [comment]
Ok. The old implementation works for:

- Shared replay is on turn 30.
- Bob: Hey, what about the clue on turn 15?
- Alice right clicks on the "Turn" text, types in 15, hits enter, which takes everyone immediately to turn 15.
- Group discusses.
- Alice clicks "Back to turn 30" button.

However, the old implementation does not work for:

- Shared replay is on turn 30.
- Bob: Hey, what about the clue on turn 25?
- Alice clicks the back button 5 times.
- Group discusses.
- Now Alice can't click the "Back to turn" button, because it is meaningless.

Similarly, the old implementation does not work for:

- Shared replay is on turn 30.
- Bob: Hey, what about the clue a few rounds back?
- Alice clicks the replay slider to go back a few turns in random increments. (Or, alternatively, Alice uses the "[" keyboard hotkey to go back via rounds.)
- Group discusses.
- Now Alice can't click the "Back to turn" button, because it is meaningless.

Propose a solution that works for all 3 use cases.

**Comment by Asddsa76** [comment]
Instead of Bob saying "on turn 20", he says "when Cathy clued/discarded/played red 2", and Alice clicks the clue log, discard pile, or red stack for the r2. 

Or a "Go to highest turn reached, except end" button. Because replay starts at last turn when the game ends. That could also be broken by people going back a few turns to look at the most recent endgame, so how about this?:

At the end of game/start of replay, highestTurn is set to 0. 

When replay goes to turn 1, highestTurn is set to 1. Then after that, highestTurn is always set to the highest turn number the replay has reached.

**Comment by Zamiell** [comment]
ok that sounds reasonable

**Comment by Zamiell** [comment]
i think this should be a shown as a little bar that slides inside the replay rectangle

**Comment by Zamiell** [comment]
i changed my mind, this is too complicated
