### ISSUE TITLE
make cards clickable in the deck/discard pile

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#51]

**Comment by Zamiell** [comment]
@rogers-j do you want to take this one

**Comment by rogers-j** [comment]
From 02/03/2018
I think the direction to take this is: 'what does the user want in these cases'?
It seems like they want to see what was going on at the time of the play/discard, so maybe the thing to do is jump back to the turn when they were about to do that?
And you could even do the same thing for the clue log
And then they can engage empathy mode like usual, in the full context, including everyone else's cards
Since I was still making team view I wasn't sure how often people would even want this.

**Comment by Zamiell** [comment]
ok whatever
