### ISSUE TITLE
Blank password and replay ID fields 

### ISSUE THREAD

**Issue by Asddsa76** [Zamiell/hanabi-live#611]
When you want to watch a specific replay or join a password-protected table, the field you write in is filled with the last thing you wrote there. You have to delete it before writing the new thing. 

Especially annoying with replay ID, since you can't just ctrl-v without erasing first.

**Comment by Zamiell** [comment]
both of these are specifically stored as cookies on the client to avoid having the user have to retype the same thing over and over.

in the case of a password, the use case is that a group will password protect their games with the same password over and over, so deleting the memory would be detrimental.

as for replays, it is useful for me to have the replay ID remembered so that I can continually go into the same replay when doing programming-related tasks

**Comment by Asddsa76** [comment]
Make them toggleable under settings?

**Comment by Zamiell** [comment]
it is too minor of a thing to justify the cost of cluttering the UI with another checkbox

**Comment by efaust** [comment]
How about making them pasted but hilighted with focus?

**Comment by Zamiell** [comment]
sure

**Comment by Zamiell** [comment]
done
