### ISSUE TITLE
ensure all command handler functions match the associated incoming command

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#636]

**Comment by Zamiell** [comment]
as well as any other things you renamed

**Comment by aliblong** [comment]
The client sends a "loaded UI" message to trigger the server sending the list of game actions. This is presumably the result of an organic evolution of the messaging story, since it seems unnecessary to couple the steps in this way. Anyway, it doesn't seem appropriate to name the command after what's triggering it (client loaded UI) rather than what it's actually doing (sending the list of game actions).

**Comment by Zamiell** [comment]
all of the command files are command handlers - they handle commands. furthermore, they are in a command handler map, which is a map that contains all of the handlers. the name of every command handler matches the name of the command that is used to initiate it. i feel that this is a logical and straightforward design. please don't arbitrarily change the server conventions that i have set up, especially without consulting me.

**Comment by Zamiell** [comment]
not an issue anymore in the merged commit
