### ISSUE TITLE
Variant proposal: Anti suit

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-live#770]
Variant idea: Anti Suit
The anti suit responds only to things that are not true 
1s respond to only 2,3,4,5
2s respond to only 1,3,4,5
3s respond to only 1,2,4,5
4s respond to only 1,2,3,5
5s respond to only 1,2,3,4

The anti suit has no color since nothing would respond to that color anyways.

**Comment by iamwhoiamhahaha** [comment]
Had the same idea few months ago. The reason why I didn't propose it here was because it looks like a Pink Suit. Nothing special. Btw, I called it a Negative Suit, a suit always touched by negative information, either negative number or negative color. But like what I said, the negative number suit looks like a pink suit, while the negative color suit looks like a white suit. I don't think it's worth it to add this new variants.

**Comment by Zamiell** [comment]
as jeff says, this sounds like a slightly-easier pink suit.
pink is already easy enough

**Comment by jakestiles** [comment]
Light pink is harder than pink. And the anti suit also has no color so it would be as hard (or harder because no Pink Promise) as light pink.

**Comment by Zamiell** [comment]
you're right. it is the same thing as light-pink, except slightly-easier, because you can now fully disambiguate anti suit cards with rank clues.

furthermore, i dont think that pink promise really affects things. a hypothetical group could arbitrarily assign "mutated pink promise", e.g. 1 --> 2, 2--> 3, 3-->4, 4-->5, 5-->1

**Comment by jakestiles** [comment]
The empathy would be fun to understand.  

Alice Clues Cathy 1 touching slot 1 and 2:
Slot 1, 2:  Normal 1s or Anti 2345.
Slot 3, 4, 5: Normal 2345 or Anti 1

Then Bob Clues Cathy 2 touching slot 2 and 3:
Slot 1: Normal 1 or Anti 2
Slot 2: Anti 345
Slot 3: Normal 2 or Anti 1
Slot 4, 5: Normal 345

**Comment by jakestiles** [comment]
Zam would you accept a PR for this?

**Comment by Zamiell** [comment]
no, i agree with jeff that it isn't substantially different enough from light pink to warrant being a variant
