### ISSUE TITLE
Variant Proposal: Wild Cards

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#801]
Add in Wild Cards that are not touched by color nor rank but plays as a random playable card.

**Comment by jakestiles** [comment]
Neat. You could also add Bombs that make you instantly lose if you play them. 

Maybe like one pink, one rainbow, one Omni, and one null bomb. And also one if each of those Wilds.

**Comment by Dr-Kakashi** [comment]
Instead of instantly losing, why not make it so that it counts as 2 strikes?  Close enough honestly xD

**Comment by jakestiles** [comment]
I think in the past when someone suggested wild cards, they said it didn’t play randomly. It played to a particular stack (I think leftmost with cards left?). I would like it to be somehow predictable so you can do finesses with them. And then every time a wild card is on finesse position, every finesse is ambiguous. Insert evil laughter.

**Comment by Zamiell** [comment]
i dont think that adding wild cards is a good idea because it increases pace. combined with the fact that it plays as any card, it just makes the game insanely easy for seasoned players. this would be a more valid variant request if there was some downside i think. jake already proposed a minesweeper variant separately, which seems reasonable, but i don't see any reason to include the wild cards with that either
