### ISSUE TITLE
Variant Proposal: Null on certain ranked cards

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#805]
Basically have a rank be unclueable by both rank and color.  For example have 5's be the target null card for the game.  Thus, all 5's are not touched by rank and color.  Would be interesting to have the rank be randomly chosen.  You'll only find out which rank is the null card when you try to clue.  

The nice thing is, if you wanted to do this in real life, you can just roll a die. Though, you would know immediately which rank is the null cards.  Could add an indicator in the game to say which rank is null.

**Comment by jakestiles** [comment]
Null 5s is already a proposal. So is Omni 1s. I made them both. :)

But I agree that it would be fun to mix and match for any rank. 

The problem is, if you try to make it unknown, are you allowing empty clues? Kakashi has a hand full of 1s and Jake is either able to clue Kakashi which turns out to touch nothing, or Jake isn’t able to clue Kakashi and Jake knows the null rank this game.

**Comment by Zamiell** [comment]
will not implement this for 2's, 3's, and 4's, at this time, as I do not think that it would not lead to very interesting gameplay over the variants i have already implemented
