### ISSUE TITLE
[Feature Request] New Variants

### ISSUE THREAD

**Issue by hellovertex** [Zamiell/hanabi-live#837]
Hi, I am currently researching learning techniques such as meta learning and Multi-Agent RL at TU Berlin. I wrote a [client](https://github.com/hellovertex/hanabi/tree/GUI) to connect our AI-agents to the hanabi-live server (running locally), to visualize the strategies they learn. 

**Did you consider adding variants/params that allow to change the number of max. info and life tokens, or the number of ranks used?**

**Comment by Zamiell** [comment]
can you clarify what you mean by "max. info" and "life tokens"?
if you want to restrict the number of ranks used, then just program your client to not use some ranks

**Comment by hellovertex** [comment]
Hey, by "max. info" and "life tokens" I mean the number of information tokens and the number of life tokens available at the start of the game resp.

Can you explain what you mean by "programming the client to not use some ranks"? Maybe I am missing something. As of now, after creating a game, I wait for the 

`notifyList [{"type":"draw","who":0,"rank":4,"suit":1,"order":0},{"type":"draw","who":0,"rank":2,"suit":4,"order":1}, ...` 

server-message and the client then responds with a json encoded 

`action {"type":0,"target":0,"clue":{"type":0,"value":2}}`
which I choose based on the content of the previous `notifyList` message. 
Not using ranks here, would be too late, since the server already dealt cards. 

The servers game creation routine, as I understand, uses parameters from my:
`gameCreate {"name":...,"variant":"...,"timed":...,"baseTime":...,"timePerTurn":...,"speedrun":...,"deckPlays":...,"emptyClues":...,"characterAssignments":...,"correspondence":...,"password":"...","alertWaiters":...}`  - message

of which only the "variant"  has influence on the cards in the deck.

**Comment by Zamiell** [comment]
> number of information tokens 

I believe that you are referring to "Clue Tokens", or just "Clues" for shorthand.
If you want to play a game with an arbitrary amount of starting clues, then you can just program your clients to only interpret server-side N clues as N-X, where X is the arbitrary clue penalty that you have chosen.

> life tokens

I believe that you are referring to "Fuse Tokens", which are referred to commonly as "strikes" or "bombs". (e.g. "3 strikes and you're out"). For the purposes of Hanabi Live, you should refer to them as strikes.

In the same way that you can have client-side different amount of clues, you can have a client-side custom strike amount. Just program the clients to terminate the game once N strikes occur.

> since the server already dealt cards.

since the amount of cards in a Hanabi deck depends on their rank, adding an extra rank to each suit is ill-defined because you would **also** have to arbitrarily choose how many of the new rank there should be.

if you want to modify the amount of cards that the server deals, then you can modify the server in the following function: https://github.com/Zamiell/hanabi-live/blob/master/src/gameDeck.go#L10-L57

historically, a variant with additional ranks has not been considered because it does not make the game harder in an interesting way

**Comment by hellovertex** [comment]
This answer all questions. Thank you very much!

**Comment by hellovertex** [comment]
Hey, is there a way I can change the number of cards dealt to the players? We would need this for evaluation of agent strategies.
