### ISSUE TITLE
Outline of non-stylished 5s don't match the number

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#901]
https://i.imgur.com/FPKbVwJ.png

By a few pixels.

**Comment by Zamiell** [comment]
@SashaIr

**Comment by SashaIr** [comment]
No clue, we didn't touch the code that draws those numbers.

**Comment by Zamiell** [comment]
in the screenshot listed, the numbers are fine. the pips are misaligned though

**Comment by SashaIr** [comment]
Well no, the filling of the numbers goes out of the border by a few pixels, that's the issue I assume. 

The pips look slightly misaligned because the yellow symbol is not a square (it's slightly wider than it is high), but they are actually not (you can check by drawing a straight horizontal line, the tip of one triangle is at the same height as the base of the other and vice versa).

**Comment by hanabirnoob** [comment]
You can see a bit of yellow being outside of the 5 outline.

**Comment by Zamiell** [comment]
oh, i see

**Comment by Zamiell** [comment]
yeah i played around with this a bit and i don't know how to fix it
its a bug in chrome because the numbers look fine in firefox
for now ill just make the color of yellow slightly darker so that it is less noticeable

**Comment by SashaIr** [comment]
But I liked this yellow. :(

**Comment by Zamiell** [comment]
its pretty close to the old yellow
