### ISSUE TITLE
postgres

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#972]

**Comment by Zamiell** [comment]
done

**Comment by zsole2** [comment]
@Zamiell, you helped earlier with database conversion issues, and this one seems even more problematic to me. 
I tried to migrate the database with pgloader, but got some  errors, e.g. "failed to find schema "hanabi" in target catalog". Then after some googling, added "ALTER SCHEMA 'hanabi' RENAME TO 'public'" and could proceed, then I got error "failed to find column public"."users"."password"...". This was the point to check and find out that the schema got altered, too, since I last updated my server (which is at commit 02e02ea, eons ago with your impressive speed of development). 

Can you suggest a good way to do the migration?

Sorry for writing in this closed issue, but did not reason to open a new one for my marginal case.

**Comment by Zamiell** [comment]
yes the schema changed as well.
rename "password" to "old_password_hash", and add password_hash.
i think thats the only schema change

**Comment by zsole2** [comment]
Thanks for the quick reply!
These pointers helped, and following them a few other columns had to be removed, too (admin, tester). After all, pgloader completed,  albeit with lots of warnings on type casting, and a few errors on some constraints. This was done with setting pgloader to "data only", though, I thought it would be better.
Finally, the site started, and loaded the past games and statistics. However, replays do not work, but I can live without it.

**Comment by Zamiell** [comment]
did you use my pgload file or are you making your own?

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/blob/ad0aa121bd9e01c3a09627a010aa7a7d18dd7c37/scripts/python/pgload_hanabi.load

**Comment by zsole2** [comment]
I missed this loadfile... After a minimal tinkering (most significantly removing users.password_hash and normalized_username, and readding them after migration), it worked.
Thanks for the help, again, and thanks for developing and maintaining this great app!!!

**Comment by Zamiell** [comment]
np

**Comment by Zamiell** [comment]
there are some more recent db changes by the way, user_friends and user_reverse_friends

**Comment by zsole2** [comment]
thanks for the info

**Comment by zsole2** [comment]
after some testing, replays work, but users' history does not. What I get is  "Error: That player does not exist in the database." But the players are clearly present in the replays, and can log in.
Fore newly created users, it works OK.

On login, I checked the users table in the database, and apparently the old_password_hash is replaced with the newer password_hash. A difference I noticed is that the normalized_username is only populated with new users, but not with the imported ones.

During import, I had to remove these two columns because of errors, and re-added afterwards. Can this be a reason? Additional note that I could not add the "normalized_username  TEXT         NOT NULL  UNIQUE" as it is in the schema, because error on add  column with NOT NULL.

**Comment by Zamiell** [comment]
oh i know why, because you have to populate the normalized_username column

**Comment by Zamiell** [comment]
yeah so what i did was, i added the column as `normalized_username column TEXT NULL`

then i wrote & ran a function in go to populate it with all the users, e.g. running the `normalizeUsername()` function for every username, and then doing a `UPDATE TABLE` blah blah

**Comment by Zamiell** [comment]
then, after that was all done, i updated `normalized_username column TEXT NOT NULL`, which should be the final state

**Comment by Zamiell** [comment]
i dont know where the golang function is that i used to do this, i think i deleted it out of the repo already. but it was really simple, only a few lines long

**Comment by Zamiell** [comment]
oh i found it by just grepping for "normalized_username" through all the git history

https://github.com/Zamiell/hanabi-live/blob/bea254fdbda671ad49403063211c72022cdb15da/src/models_users.go#L182-L216

so run this function and it will populate the users. its a temp thing, which is why its only in an old commit

**Comment by Zamiell** [comment]
btw, the point of all of this is that prevents phishing attacks using unicode characters, i would imagine that facebook, google, etc. use a similar technique

**Comment by zsole2** [comment]
Thanks, I'll do this soon. Maybe not the golang thing, but rather go manual in the database... I'm not a programmer, just trying to understand what I find by googling and take it from there. Fortunately there are not too many users in our small club.

**Comment by Zamiell** [comment]
oh yeah if you only have like 5-10 people then you can just do it by hand
as long as there are no special characters and all ASCII, then normalized_username is just the lowercase version and thats it

**Comment by zsole2** [comment]
It appears to be everything working, thanks a lot!!!

**Comment by Zamiell** [comment]
np

**Comment by zsole2** [comment]
Oopps... Everything appeared OK, except now trying to use it,  the finished  game is not stored in the database... How can I troubleshoot it?

**Comment by Zamiell** [comment]
what are the errors in the log

**Comment by zsole2** [comment]
Sorry, bad alert...  No results appeared in the chat log, and panicked. Then checked the log, and the db, and the games are there. Then I  just remembered that you have  removed the completed game results from the chat log... Everything seems fine.

**Comment by Zamiell** [comment]
Hah. Yeah I removed that bcuz it was getting too spammy

**Comment by Zamiell** [comment]
Btw there will be some more database changes next week. All the variant IDs need to be remapped

**Comment by Zamiell** [comment]
after i update hanabi live variants.json, you are going to have to run create_variants.py with a copy of the old variants.json, that will give you a list of DB queries to run in order to transition the DB

and this same process will need to be repeated whenever i add any variants, cuz the variant IDs will change again.

this is because variants.json is not going to be created by hand anymore, managing a 19K line file by hand is too much

**Comment by zsole2** [comment]
thanks for the heads up, I'll watch for the changes
