### ISSUE TITLE
https://boardgamegeek.com/boardgame/290357/hanabi-grands-feux

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#974]

**Comment by robertos** [comment]
I'd be interested in taking a stab at implementing this. @Zamiell I imagine you're talking about the Black Powder variant?

If so, I think it could be developed in parts:
1. Add the ability to have a suit be reversed (three 5's and one 1, must be played 5 -> 1). That would allow already for hundreds of new variants since Reversed (or "Upside-Down") is a property like Dark or Null.
2. In this particular case, the variant is "Reversed White (6 suits)". Optionally, Reversed White can be renamed or aliased in the list as "Black Powder" as a special case. 
3. There's a special scoring, which is to make the score start at -5 (i.e. max score is 25 even though there are 6 suits, each card not played from the special suit is a -1). I don't think this is necessary, since it's just changing the initial score and doesn't affect the game at all.
4. If desired, reversed suit(s) can have some visual treatment / icon. 

Rules (in French): https://www.philibertnet.com/en/index.php?controller=attachment&id_attachment=3851

**Comment by Zamiell** [comment]
sure, go for it

**Comment by Zamiell** [comment]
its faster to talk to me in discord btw

**Comment by robertos** [comment]
OK, I'll find you there if/when I get to this (BTW, this was definitely fast enough 😄)

**Comment by Zamiell** [comment]
right now i think master is bugged, you might want to fork from the version from 4 days ago

**Comment by Zamiell** [comment]
done-ish
