### ISSUE TITLE
feature request : bot API

### ISSUE THREAD

**Issue by tyrcho** [Zamiell/hanabi-live#976]
I've started work on a hanabi bot and I'd love to have it play here. After a few days it's already able to score 10-15 points on regular games.

Would you like to offer an API for bots to play on the site ? 

I really like what lichess did in this area:
- an account can be upgraded to bot status (and is then clearly marked this way) https://lichess.org/api#operation/botAccountUpgrade
- then the bots have a few endpoints to join a game and to play

I could help with the design of the API if you're interested, I'm into that for work.

**Comment by Zamiell** [comment]
hanabi live already "supports" bots. you can just have it listen to the websocket server in exactly the same way that the client does.

what specifically would the hypothetical bot api even do

**Comment by tyrcho** [comment]
OK, that's fine then ! Most gaming sites prevent bot usage but if you don't mind ...

I'll label it explictely so people are not surprised, and test it with myself first.

is there some sort of documentation about the possible JSON messages exchanged on the WS ? I searched the repository and found nothing.

Otherwise I can always debug with my browser ...

**Comment by Zamiell** [comment]
>  Most gaming sites prevent bot usage but if you don't mind ...

for now, i don't mind. hanabi live is a really small website, but maybe that will change in the future

> I'll label it explictely so people are not surprised, and test it with myself first.

lets prefix our bots with a "Bot-" prefix as a convention. im planning on writing code to make it so that bots can join unlimited games instead of just one at a time.

> is there some sort of documentation about the possible JSON messages exchanged on the WS ?

there's no documentation currently, youll have to read the source. which is neatly organized so it shouldn't be so bad. but i would just look at the code for this instead: https://github.com/Zamiell/hanabi-live-bot

**Comment by tyrcho** [comment]
the python sample is perfect, thanks a lot !
