### ISSUE TITLE
colorblind cards tilt

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#977]

**Comment by Zamiell** [comment]
looks real fuckin bad

**Comment by tyrcho** [comment]
maybe some neutral color (white or black) to outline clued cards ?

it's confusing for me because clued cards are highlighted with some color which looks very similar to green and yellow cards. So I only pay attention when clues land on Red/green/purple ...

I misplayed again yesterday because I couldn't see properly that a card already got a clue

**Comment by Zamiell** [comment]
> it's confusing for me because clued cards are highlighted with some color which looks very similar to green and yellow cards

i changed this to black already. its not uploaded yet to the live website yet though

**Comment by Zamiell** [comment]
it will be uploaded either today or tomorrow and then you can tell me again what you think

**Comment by tyrcho** [comment]
I saw the black borders yesterday and it's much more visible, thanks @Zamiell !
